env:
  parameter-store:
    DOCKER_HUB_USERNAME: "docker_hub_username"
    DOCKER_HUB_PASSWORD: "docker_hub_password"
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t shafrian/html-nginx:latest -t shafrian/html-nginx:1.1.
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - echo Build stage successfully completed on `date`
      - echo Pushing the Docker image...
      - docker push -a shafrian/html-nginx
      - echo Success